name: API CI - Newman tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install newman
        run: npm install -g newman

      - name: Run Newman collection
        run: |
          newman run postman_collection.json -e postman_environment.json --reporters cli,junit --reporter-junit-export newman-results/results.xml
        shell: bash

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: newman-results
          path: newman-results/results.xml